---
- hosts: nfs
  become: yes

  vars:
    share_path: /mnt/nfsroot

  tasks:
    - name: Install nfs
      package:
        name: nfs-utils
        state: latest
    
    - name: Start and enable nfs-server
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: Configure exports
      template:
        src: /home/ansible/exports.j2
        dest: /etc/exports
      notify: Update nfs
  
  handlers:
    - name: update nfs exports
      command: exportfs -a
      listen: Update nfs


- hosts: remote
  become: yes

  vars:
    nfs_ip: "{{ hostvars['nfs']['ansible_default_ipv4']['address'] }}"
    nfs_hostname: "{{ hostvars['nfs']['ansible_hostname'] }}"
  vars_files:
    - /home/ansible/user-list.txt

  tasks:
    - name: Configure hostfile
      template:
        src: /home/ansible/etc.hosts.j2
        dest: /etc/hosts.nfslab

    - name: Get file status
      stat:
        path: /opt/user-agreement.txt
      register: filestat

    - name: Debug info
      debug:
        var: filestat

    - name: Create users
      user:
        name: "{{ item }}"
      when: filestat.stat.exists
      loop: "{{ users }}"
